# See https://pre-commit.com/ for usage and config
repos:
- repo: local
  hooks:
  - id: isort
    name: isort
    stages: [commit]
    language: system
    entry: bash -c "PIPENV_VERBOSITY=-1 pipenv run isort"
    types: [python]

  - id: black
    name: black
    stages: [commit]
    language: system
    entry: bash -c "PIPENV_VERBOSITY=-1 pipenv run black"
    types: [python]

  - id: flake8
    name: flake8
    stages: [commit]
    language: system
    entry: bash -c "PIPENV_VERBOSITY=-1 pipenv run flake8"
    types: [python]
    exclude: setup.py

  - id: bandit
    name: bandit
    stages: [commit]
    language: system
    entry: bash -c "PIPENV_VERBOSITY=-1 pipenv run bandit -r ."
    types: [python]
    exclude: setup.py

  - id: mypy
    name: mypy
    stages: [commit]
    language: system
    entry: bash -c "PIPENV_VERBOSITY=-1 pipenv run mypy"
    types: [python]
    pass_filenames: false

  - id: pytest
    name: pytest
    stages: [commit]
    language: system
    entry: bash -c "PIPENV_VERBOSITY=-1 pipenv run pytest"
    types: [python]
    always_run: true
    pass_filenames: false

  - id: pytest-cov
    name: pytest
    stages: [push]
    language: system
    entry: bash -c "PIPENV_VERBOSITY=-1 pipenv run pytest --cov"
    types: [python]
    pass_filenames: false

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.3.0
  hooks:
  -   id: check-added-large-files
  -   id: check-merge-conflict
  -   id: debug-statements
  -   id: detect-private-key
